server:
  port: 8081

spring:
  application:
    name: pest-identification-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 120.79.146.15:8848
      config:
        enabled: false

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: consumer
          uri: lb://pest-identification-consumer
          predicates:
            - Path=/**
      httpclient:
        connect-timeout: 3000
        response-timeout: 10000